// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACI2dNQN2x373l6LilG3qFuDsjcjnw0Vk',
    appId: '1:249297899757:web:34980a2f1e2ffe9c4bbce4',
    messagingSenderId: '249297899757',
    projectId: 'ecommerceapp-54c48',
    authDomain: 'ecommerceapp-54c48.firebaseapp.com',
    storageBucket: 'ecommerceapp-54c48.appspot.com',
    measurementId: 'G-QF5BF7KNK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6k722QVaCBr-7pAgDAHPobqenjI9S3gs',
    appId: '1:249297899757:android:eb2730f93a0960484bbce4',
    messagingSenderId: '249297899757',
    projectId: 'ecommerceapp-54c48',
    storageBucket: 'ecommerceapp-54c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKFKcw0NGkuku5-VDt-5ftTKm6rG_pWWA',
    appId: '1:249297899757:ios:c398aeb93003a3294bbce4',
    messagingSenderId: '249297899757',
    projectId: 'ecommerceapp-54c48',
    storageBucket: 'ecommerceapp-54c48.appspot.com',
    androidClientId: '249297899757-su0j1qtcs4f3fv9r6d1boiq1um6n4pq1.apps.googleusercontent.com',
    iosClientId: '249297899757-j2rgmb5i8qnk3p7kfq7jcmiusp5n5npu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}